trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'


variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release|Debug'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'


steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Building Broker'
  name: 'CompileBroker'
  inputs:
    solution: '$(solution)'
    projectFile: '**/Broker.vcxproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    logFileVerbosity: 'detailed'
    

- task: VSBuild@1
  inputs:
    platform: 'x86|x64'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
    projectFile: '**/GUI.vcxproj'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
