# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  solution: 'CFB.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release|Debug'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

jobs:
- job: 'Build_Broker_Windows64'
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: MSBuild@1
    displayName: 'Build Broker 64-bit'
    inputs: 
      msbuildArguments: '-nologo /m /p:Configuration=Release'
      solution: CFB.sln
  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './build'
      artifactName: win64build
