name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      NB_CPU: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NB_CPU
      shell: pwsh
      run: |
        echo "NB_CPU=$env:NUMBER_OF_PROCESSORS" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Configure (CMake)
      shell: pwsh
      run: |
        mkdir build
        cmake -S . -B build -A x64

    - name: Build (CMake)
      shell: pwsh
      run: |
        cmake --build build --config Release --parallel $env:NB_CPU

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SANGJUN_driver_${{ github.sha }}
        path: |
          build/Sangjun/Release/SANGJUN.sys
          build/Sangjun_wdf/Release/SANGJUN_wdf_driver.sys
        retention-days: 1
